### ISSUE TITLE
Can't change options

### ISSUE THREAD

**Issue by sanmadjack** [JeodC/PortMaster-Descent#6]
I'm running this on an anbernic rg35xx h, and just about everything works great, but I can't change any of the in game options. The check boxes etc don't react to any of the buttons, including the start button. Am I missing something?

**Comment by sanmadjack** [comment]
I changed the gptk file so that l3 inputs a space, which is (to my knowledge) what the option menus respond to, and that's working so far. Something built-in would probable be a good idea.

**Comment by JeodC** [comment]
> I changed the gptk file so that l3 inputs a space, which is (to my knowledge) what the option menus respond to, and that's working so far. Something built-in would probable be a good idea.

The checkboxes in the options menu respond to the joystick inputs, which should be x or y. It might not work on some specific devices, in which case modifying the gptk to add a space action as you did would be the solution.

**Comment by sanmadjack** [comment]
You appear to be correct here, none of my device buttons are sending joystick buttons 1 or 2, so the games can't respond. Such is life, thanks for the info.
